name: Infra CD - Deploy All Microservices

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  ORG_NAME: USER-POLYGLOT
  REPOS: backend frontend ai
  NAMESPACE: default
  INFRA_DIR: first  # Directory containing HPA, metrics-server, ingress, etc.

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      # 1️⃣ Checkout infra repo (this repo)
      - name: Checkout Infra Repo
        uses: actions/checkout@v4

      # 2️⃣ Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # 3️⃣ Apply infra manifests first (HPA, metrics-server, ingress)
      - name: Apply Infra Manifests
        run: |
          echo "Applying infra manifests..."
          kubectl apply -f $INFRA_DIR/ -n $NAMESPACE

      # 4️⃣ Checkout all microservice repos dynamically
      - name: Checkout Microservice Repos
        run: |
          for repo in $REPOS; do
            echo "Checking out $repo"
            gh repo clone $ORG_NAME/$repo $repo
          done
        env:
          GH_TOKEN: ${{ secrets.ORG_PAT }}

      # 5️⃣ Deploy each microservice
      - name: Deploy Microservices
        run: |
          for repo in $REPOS; do
            echo "Deploying $repo..."
            kubectl apply -f $repo/kubernetes/ -n $NAMESPACE
            for deployment in $(kubectl get deployments -n $NAMESPACE -o jsonpath='{.items[*].metadata.name}'); do
              kubectl rollout status deployment/$deployment -n $NAMESPACE
            done
          done

      # 6️⃣ List all pods to verify deployment
      - name: Get All Pods
        run: |
          echo "Listing all pods in namespace $NAMESPACE:"
          kubectl get pods -n $NAMESPACE -o wide
